version: '3'
services:
  galgo-mutau-database:
    image: mongo

  galgo-mutau-client:
    image: nginx
    links:
      - galgo-mutau-server
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/dist:/usr/share/nginx/html

  galgo-mutau-server:
    build: ./server
    depends_on:
      - galgo-mutau-database
    links:
      - galgo-mutau-database
    environment:
      - SECRET=foo
    ports:
     - 8080:8080
