version: '3'
services:
  galgo-mutau-database:
    image: mongo

  galgu-mutau-client:
    image: ngnix
    links:
      - galgo-mutau-server
    ports:
      - 80:80
    volumes:
      - ./client/dist:/usr/share/nginx/html

  galgo-mutau-server:
    build: ./server
    depends_on:
      - galgo-mutau-database
    links:
      - galgu-mutau-database
    environment:
      - SECRET=foo
    ports:
     - 3000:3000
